### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by tom0023** [tom0023/chat-space#8]
#IPアドレス
13.114.114.187

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう**
<img width="1431" alt="自動更新" src="https://user-images.githubusercontent.com/49669977/86902498-004c5f80-c149-11ea-9f09-c0b2a661fa2c.png">



修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by tom0023** [comment]
修正しましたのでご確認お願いします！

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by tom0023** [comment]
ありがとうございます！
